language: python
python:
  - "2.7"
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgeos-dev python-numpy
  - sudo apt-get install -y libgdal1h gdal-bin libgdal-dev
  - sudo apt-get install libproj-dev libproj0 proj-bin
  - pip install --install-option="--no-cython-compile" cython
install:
  - "pip install -r requirements.txt"
script: 
  - "python setup.py install"
  - "python test/gdltesting.py"
